### ISSUE TITLE
Ошибка скрипта

### ISSUE THREAD

**Issue by toperx** [tarampampam/mikrotik-hosts-parser#10]
Скрипт начал падать в ошибку т.к. адрес с 

_Cервисы телеметрии от MS_  
http://www.crazyws.fr/WindowsSpyBlocker/hosts/win7/spy.txt

Выдаёт 404

**Comment by sasha2002** [comment]
Проект перекочевал сюда :
https://github.com/crazy-max/WindowsSpyBlocker

https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt

**Comment by tarampampam** [comment]
Новый путь: `https://cdn.rawgit.com/crazy-max/WindowsSpyBlocker/889dce20/data/hosts/spy.txt`

Оба хоста, где приложение крутится - поправил. Спасибо за обратную связь, друзья :)

Задачу закрываю.
