### ISSUE TITLE
Исходники листов у которых IP-адрес записан как long integer не парсятся

### ISSUE THREAD

**Issue by vadimpronin** [tarampampam/mikrotik-hosts-parser#119]
Исходники листов у которых IP-адрес записан как long integer (например "0 host.com" вместо "0.0.0.0 host.com") не парсятся.

Long integer - валидный формат записи IP-адреса (например 1.1.1.1 может быть записан как 16843009, а 0.0.0.0 просто как 0), принимающийся всеми операционными системами (включая RouterOS) в том числе и для hosts-файлов.

Пример листа составленного в таком формате: https://raw.githubusercontent.com/luxysiv/Blockads/master/iOS/Hosts
Это небольшой лаконичный блок-лист для рекламы на iOS-устройствах без сотен лишних записей, которые могут перегрузить слабые роутеры

**Comment by tarampampam** [comment]
Hi @vadimpronin and thanks for your issue!

Could you please prepare the PR with the required changes? Currently, I have no enough time for this project, and my implementation of this feature can take a long time :(

**Comment by vadimpronin** [comment]
Please take a look at the PR https://github.com/tarampampam/mikrotik-hosts-parser/pull/123

**Comment by tarampampam** [comment]
@vadimpronin Thanks for your PR! Release will be shortly!

**Comment by tarampampam** [comment]
[v4.4.0 released](https://github.com/tarampampam/mikrotik-hosts-parser/releases/tag/v4.4.0)!
