### ISSUE TITLE
not all banners are blocked.

### ISSUE THREAD

**Issue by Sheicer** [tarampampam/mikrotik-hosts-parser#12]
Hello. When using a script on Youtube, not all banners are blocked. What could be the problem?
![banner](https://user-images.githubusercontent.com/42835693/44847399-0bd0c480-ac5c-11e8-8a92-c70fe5969aff.jpg)

**Comment by tarampampam** [comment]
Maybe Youtube uses new "ad" hosts. Can you debug this by itself and tell to me results?

**Comment by Vaippp** [comment]
No. I can't.

**Comment by cintex** [comment]
Добрый день,
Скрипт сгенерированный на https://stopad.cgood.ru/ не отрабатывает список http://adaway.org/hosts.txt
Скрипт сгенерированный на https://stopad.hook.sh/ отрабатывает штатно, но в нем есть строчка `:delay 3s;`, возможно в этом дело.
Остальные списки отрабатываются нормально и в первом и во втором варианте.

**Comment by Vaippp** [comment]
Здравствуйте.
Скрипт отрабатывает нормально (адреса добавляются в static DNS) проблема в том, что реклама блокируется частично (только на главной странице и банер справа). В самом видео на желтых маркерах она воспроизводится + неблокируются всплывающие баннеры в окне видео. 
Мб проблема у меня, у Вас данный скрипт блокирует всю рекламу полностью?

**Comment by cintex** [comment]
Нужно пару дней на проверку, недавно заметил что реклама просто атаковала, начал разбираться, оказалось была ошибка загрузки списков, затыкалось на списке http://adaway.org/hosts.txt, в статик ДНС было всего 1200 записей. Заменил скрипт, сейчас ~16000 адресов в статик ДНС

**Comment by Vaippp** [comment]
Спасибо, буду ждать результатов.

**Comment by Vaippp** [comment]
> Нужно пару дней на проверку, недавно заметил что реклама просто атаковала, начал разбираться, оказалось была ошибка загрузки списков, затыкалось на списке http://adaway.org/hosts.txt, в статик ДНС было всего 1200 записей. Заменил скрипт, сейчас ~16000 адресов в статик ДНС
Реклама на YouTube.com, Skype и пр.  
Cервисы телеметрии от MS  
~400 записей  
~1500 записей  
~2400 записей  
~12000 записей  
~13000 записей  
~45000 записей  
Скажите какие галочки предпочтительней выставлять для получения списка из ~16000 адресов?

**Comment by tarampampam** [comment]
Я бы рекомендовал отталкиваться от качества, а не количества. "Пошерстить" форумы - такие вещи часто обновляются, и как вариант - можете собрать свой список, разместить его на github.com, и подключить его используя rawgit.com. Таким образом, делая один коммит вы можете управлять блэк-листом, например, на N-маршрутизаторов целой компании ;)

**Comment by tarampampam** [comment]
Хорошо, как будет возможность, я постараюсь проверить всё на своём маршрутизаторе и обновлю при необходимости список хостов в имеющихся листах

**Comment by Vaippp** [comment]
> @cintex на завтра запланировал апдейт `stopad.cgood.ru` - если всё пройдёт удачно - и там будет свежая версия

Как обстоят дела с новой версией?

**Comment by tarampampam** [comment]
Пока не удаётся синхронизироваться по времени с администратором ресурса, часовые пояса сильно разнятся. Сегодня попробую ещё раз

**Comment by tarampampam** [comment]
@Vaippp https://stopad.cgood.ru/ обновлён успешно, проверяй

**Comment by Vaippp** [comment]
> @Vaippp https://stopad.cgood.ru/ обновлён успешно, проверяй

![ad](https://user-images.githubusercontent.com/42835693/45605552-79476800-ba46-11e8-9261-f02f1a62a0b3.jpg)

Создается список с 3045 адресами.

**Comment by tarampampam** [comment]
Встретил следующие ошибки (выводятся в начале генерируемого скрипта):

```
## Sources cache state: enabled, *response* cache lifetime: 240
## Cache: "https://cdn.rawgit.com/crazy-max/WindowsSpyBlocker/889dce20/data/hosts/spy.txt" loaded from cache
## Error :: http://adaway.org/hosts.txt :: cURL error 28: Connection timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
## Cache: "http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext" loaded from cache
## Error :: http://someonewhocares.org/hosts/hosts :: cURL error 28: Connection timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
## Script generated 2018-09-17 05:21:54
```

Буду разбираться

**Comment by cintex** [comment]
Скрипт с https://stopad.cgood.ru/  отработал нормально.
 /system script run AutoADBlock
      status: finished
  downloaded: 182KiBz pause]
       total: 182KiB
    duration: 1s
В результате 3070 Items in static DNS.

**Comment by Vaippp** [comment]
Сегодня с текущими адресами перестал синхронизироваться google chrome.

**Comment by tarampampam** [comment]
@Vaippp странно, у меня с ними всё работает. Необходимо больше информации для диагностики

**Comment by cintex** [comment]
На прошивке 6.44 скрипт с описанными правами не запускался по расписанию, ошибка в логах - недостаточно прав. Установил в скрипте Don`t Require Permission - стал отрабатываться нормально.
По факту - реклама в ютубе на телевизоре и планшетах все равно идет (может и меньше) перед запуском видео и врезками внутри видео.

**Comment by Vaippp** [comment]
> @Vaippp странно, у меня с ними всё работает. Необходимо больше информации для диагностики
Не синхронизируются закладки и папки в google chrome. При удалении адресов из ДНС, все нормально.

**Comment by Vaippp** [comment]
Методом исключения определил, что синхронизация не происходит из-за адреса: 172.217.10.238, но у этого адреса постоянно меняются домены.

**Comment by Vaippp** [comment]
Проблема с синхронизацией решена. 
Вот из-за этих адресов: googleapis.l.google.com clients.l.google.com

**Comment by KobzarSergey** [comment]
Пожалуйста,уточните,решена ли проблема с блокировкой рекламы на ютюбе? От такого количества рекламы начинает тошнить...

**Comment by tarampampam** [comment]
В данный момент работаю над переписыванием данного приложения на GoLang, и новая версия будет включать в себя исправления всех известных ошибок

**Comment by KobzarSergey** [comment]
На какую дату планируется релиз?

**Comment by tarampampam** [comment]
Пока рано говорить (оффлайн работа отнимает львиную долю времени), но постараюсь как можно скорее

**Comment by LukaS0lncev** [comment]
Добрый день, а проблема с рекламой на ютубе (тв, планшеты), через официальный софт ютуба решится? может есть адреса, которые нужно добавить вручную и их нет в списке? я и форумные списки перепробовал... не помогает. Спасибо заранее

**Comment by KobzarSergey** [comment]
Возможно, есть какие-то новости ?

**Comment by tarampampam** [comment]
Есть - прогадали :)

Пока небольшая пауза в разработке проекта из-за работы.

**Comment by tarampampam** [comment]
@KobzarSergey сегодня выпустил новую мажорную версию (`v3.*`) - попробуйте обновиться, и если проблемы будут воспроизводиться - создайте новый issue, пожалуйста
