### ISSUE TITLE
regexp в источнике

### ISSUE THREAD

**Issue by TerAnYu** [tarampampam/mikrotik-hosts-parser#14]
Здравствуйте!
Интересует возможность указания своего источника, где будет указано не name и ipaddress, а regexp и ipaddress.
Например, для блокировки рекламы на LG SmartTV (возможно список не полный) использую такие строки:

```
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?smartclip.net" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?smartclip.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?smartshare.lgtvsdp.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?ibis.lgappstv.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?ad.lgappstv.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?yumenetworks.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?doubleclick.net" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?llnwd.net" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?ad.lgsmartad.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?lgsmartad.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?quantserve.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^(.*.)\?scorecardresearch.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=yes name="" regexp="^(.*.)\?lgtvsdp.com" ttl=1d
/ip dns static add address=127.0.0.1 disabled=no name="" regexp="^lgad(.*.)" ttl=1d
```

**Comment by tarampampam** [comment]
Доброго времени суток! В данный момент работаю над переписыванием приложения на  GoLang, и подумаю над реализацией данного функционала

**Comment by wl2776** [comment]
Кажется, это NP-полная задача. 

https://cstheory.stackexchange.com/q/1854

**Comment by tarampampam** [comment]
К сожалению, в новую мажорную версию запрошенный функционал не вошел, но реализованы структуры с поддержкой регулярных выражений. Имеется ли у вас навык разработки на golang? Быть может попробуете самостоятельно реализовать данный функционал?

**Comment by TerAnYu** [comment]
К сожалению я не знаю Golang и не пробовал его в работе.

**Comment by tarampampam** [comment]
Регулярки опасно использовать, так как если напороть в экранировании специальных символов или кавычках - можно запороть маршрутизатор одним легким движением.

**Comment by tarampampam** [comment]
С hosts-файлами всё довольно просто и надежно

**Comment by TerAnYu** [comment]
Так это же регулярки для DNS, а не для L7 (вот в нём - L7, точно можно запороть, сам так иногда делал)

**Comment by tarampampam** [comment]
А публичных листов с регулярками доменов в сети достаточно? Ранее их не встречал

**Comment by TerAnYu** [comment]
Извините, но не понял вашего вопроса.
Я имел ввиду что сократить список, например:

> add address=127.0.0.1 comment="ADBlock" disabled=no name="707.bapi.adsafeprotected.com"
> add address=127.0.0.1 comment="ADBlock" disabled=no name="7093.bapi.adsafeprotected.com"
> add address=127.0.0.1 comment="ADBlock" disabled=no name="7202.bapi.adsafeprotected.com"
> add address=127.0.0.1 comment="ADBlock" disabled=no name="7246.bapi.adsafeprotected.com"
> add address=127.0.0.1 comment="ADBlock" disabled=no name="7250.bapi.adsafeprotected.com"
> add address=127.0.0.1 comment="ADBlock" disabled=no name="7251.bapi.adsafeprotected.com"
> add address=127.0.0.1 comment="ADBlock" disabled=no name="7882.bapi.adsafeprotected.com"
можно указать regexp: **`(.*?).bapi.adsafeprotected.com`** и вышеперечисленные хосты попадут в этот список, но это, наверное, надо делать в самом **mikrotik-hosts-parser** и производить такие операции.

**Comment by tarampampam** [comment]
В данный момент у приложения основная фича в том, что любой может указать URI до публичных файлов хостов "рекламной направленности", и приложение из этих списков хостов формирует скрипт для микротика "на лету". Если реализовывать аналогичный функционал для регулярок - нужно будет поддерживать или свои файлы хостов в котором хосты указываются именно как регулярки (а не доменные имена), или использовать какие-либо публичные, чтоб сообщество их поддерживало всегда в актуальном состоянии, а у тебя на маршрутизаторе они всегда были в актуальном состоянии.

Реализация механизма поддержки указания хостов в виде регулярок была бы особенно полезна в том случае, если уже умеют место быть такого рода списки хостов в виде регулярок, которые сообщество поддерживает в актуальном состоянии.

Отсюда вопрос - имеются ли у вас какие-либо примеры данных списков?

**Comment by tarampampam** [comment]
```
add address=127.0.0.1 comment="ADBlock" disabled=no name="(.*?).bapi.adsafeprotected.com"
```

Является не корректной записью, на сколько помню. Верный формат:

```
add address=127.0.0.1 comment="ADBlock" disabled=no regexp="(.*?).bapi.adsafeprotected.com"
```

**Comment by tarampampam** [comment]
Автоматически конвертировать существующие списки статических доменов (вида `1.a.com`, `2.a.com`) в наборы регулярных выражений (вида `.*\.a\.com`, или всё таки `\d{1}\.a\.com`?) для его сокращения - даже не представляю себе как это возможно сделать, очень сложный алгоритм принятия данного решения видится.

**Comment by TerAnYu** [comment]
Списков с регулярками у меня нет и не встречал.
Но есть публичные, которые вы и используете, вот я предлагал парсить их вашим приложением, что бы уменьшить список, возможно задать разную степень уменьшения (минимальная - хосты как есть в списках, максимальная, до уровня поддомена третьего/второго уровня, например, **654564564.bapi.adsafeprotected.com** и до **(.*?).adsafeprotected.com**).

Да, вы правильно указали что надо вместо **name=** использовать **regexp=**, тут я не проверил.

Алгоритм, наприме такой (скорее всего точно не верный):
сравниваем с последнего символа до первого, если сравнение максимальное (почти полностью совпадает между октетами) и только небольшая часть различается, тогда эту часть и объединяем.

Да, оказывается не все возможности regexp используются  .....

Если что, то можно и закрыть эту исуську.

**Comment by tarampampam** [comment]
Хорошо, этот issue я закрываю, но в уме возьму "на карандаш" что такой функционал был бы востребован. Возможно, по истечении некоторого времени что-то будет придумано, но пока что нет оформленной идеи как построить алгоритм данных преобразований.

Спасибо за интересный вопрос!
