### ISSUE TITLE
MikroTik StopAD выдает ошибку загрузки

### ISSUE THREAD

**Issue by burza69** [tarampampam/mikrotik-hosts-parser#15]
Здравствуйте! делал все как написано но выбивает ошибку, что не так? https://s8.hostingkartinok.com/uploads/images/2018/09/b23fce8ffa9348b319544304dd0dc8c4.png

**Comment by burza69** [comment]
Прошивка 6.43.2

**Comment by cintex** [comment]
Попробуйте поставить галочку "Don't require permission"

**Comment by burza69** [comment]
всё также

**Comment by Winand** [comment]
@burza69 посмотрите вручную, что сервер выдаёт по ссылке внутри скрипта? Может он того, умер.

**Comment by rzrwolf** [comment]
Аналогичная ситуация с прошивкой 6.43.x - AD block script download FAILED.

Сервер выдает список, но в микротике не прописывается ничего.

**Comment by rzrwolf** [comment]
Разобрался, не хватало свободного места под бекап конфига

**Comment by mvn77** [comment]
та же беда - не могу никак победить....

**Comment by tarampampam** [comment]
В данный момент работаю над переписыванием данного приложения на GoLang, и новая версия будет включать в себя исправления всех известных ошибок

**Comment by tarampampam** [comment]
Пожалуйста, попробуйте обновленную версию приложения (`v3.*`), и если ошибку будут воспроизводиться и дальше - откройте новый issue
