### ISSUE TITLE
StopAD ошибка выполнения на символе "

### ISSUE THREAD

**Issue by popowsergei** [tarampampam/mikrotik-hosts-parser#2]
нашёл косячную строчку в скрипте StopAD
в скрипт попадет строка вида
add address=255.0.0.0 name=machine.domain.tld". comment=ADBlock
а жалуется на ошибку 
expected end of command (line 3979 column 46)
т.е. на символ — "
данная строка попадает из последнего источника с 45 тыс строк

причём в исключения добавляю но не срабатывает
пробовал
machine.domain.tld".
machine.domain.tld"
machine.domain.tld

ещё в скрипт попадет куча строк вида
add address=255.0.0.0 name=] comment=ADBlock
add address=255.0.0.0 name=# comment=ADBlock
но они проходят без ошибок и работе скрипта не мешают

**Comment by tarampampam** [comment]
Поправил, коммит: e816c5a4143f316a9a2a769cb0fed74bcc30e200

Раскатал обновление на обоих серверах.

Сабж закрываю, спасибо за репорт
