### ISSUE TITLE
MikroTik StopAD проблема: не резолвится домен youtube-nocookie.com

### ISSUE THREAD

**Issue by DragonSerW** [tarampampam/mikrotik-hosts-parser#210]
Ребята, здорова!
youtube-nocookie.com пингуется с адресом 127.0.0.1.
Приделывал StopAD к Микротику `ac3` через https://stopad.cgood.ru/.
Не проигрываются видео в веб-страницах https://www.apachefriends.org/ и https://dragonserw.ru/contact-us.

**Comment by DragonSerW** [comment]
Проблема ушла, огромное спасибо! :-))
Но теперь я не могу открыть https://play.google.com/store/apps/details?id=com.collabora.libreoffice.

**Comment by DragonSerW** [comment]
Проблема с Ютюбом опять повторилась.
Поправить? :-))

**Comment by tarampampam** [comment]
Since this issue is not related to the service (the end user manages host lists), I'll be closing this issue

**Comment by DragonSerW** [comment]
Доброй ночи!
Так я так и не понял, как решается моя проблема?
youtube-nocookie.com пингуется как 127.0.0.1 :-(
