### ISSUE TITLE
How should I disable Yandex Direct advertisements?

### ISSUE THREAD

**Issue by DragonSerW** [tarampampam/mikrotik-hosts-parser#220]
Hello!
On the page https://musictxt.ru/ru/w/wladimir_kuzmin/text/7_morei.htm I can see such advertisements: https://splash.org.ru/~SerW/Temp/tarampampam/output-Downsample.pdf.

**Comment by TerAnYu** [comment]
@DragonSerW это мусор от яндекса, это можно заблокировать только с самим яндексом. 
This is garbage from Yandex, it can be blocked only with Yandex itself.

**Comment by DragonSerW** [comment]
А подскажите плиз, как именно?
Оплатив Плюс?
Яндексу платить не хочу.
Кстати, у меня оплачено размещение в Картах.

**Comment by TerAnYu** [comment]
Реклама яндекса не использует отдельный домен, а отдельный подкаталог - https://yandex.ru/ads
Использую только для браузера плагин uBlock Origin.
Для других устройств или приложений не знаю как это использовать, кроме MITM прокси, который расшифрует трафик, заблокирует всё, что попадает под критерий https://yandex.ru/ads/*, но это будет подмена сертификата и большинство приложений или устройств не примут такое соединение без нового CA сертификата.

**Comment by tarampampam** [comment]
Since this issue is not related to the service (the end user manages host lists), I'll be closing this issue
