### ISSUE TITLE
Заканчивается оперативная память на mikrotik

### ISSUE THREAD

**Issue by GooG2e** [tarampampam/mikrotik-hosts-parser#3]
Здравствуйте!
Возникла проблема когда при добавлении большого количества записей заканчивается оперативная память, после этого роутер перезагружается.
Как вариант было бы неплохо загружать списки частями. При 64Мб RAM можно загрузить около 9000  dns записей без возникновения проблем

**Comment by tarampampam** [comment]
Об этом и писал на хабре. Цитата:
> Эмпирически доказано что при импортировании ~5500 записей Mikrotik hAP lite (650MHz @ RAM 32 Mb) встает почти колом при попытке в GUI открыть таблицу статических маршрутов. Перезагрузка помогает

Ссылка: https://habrahabr.ru/post/264001/
