### ISSUE TITLE
на версии 6.46.5 stable  не работает.

### ISSUE THREAD

**Issue by kartozar** [tarampampam/mikrotik-hosts-parser#41]
на версии 6.46.5 скр ипт не работает. я пробовал уже непосредственно тот скрипт где добавляются хосты, и ошибка в строке 6 после чего не работает. #38 #

**Comment by kartozar** [comment]
а строка 6 вот так выглядела: add address=127.0.0.1 comment="ADBlock" disabled=no name="180hits.de"

по нажатии кнопки ок просто висит, и сверху пишет not invalid,  а по нажатию кнопки aply, выдает ошибку в строке 6.

**Comment by tarampampam** [comment]
Слишком мало информации, не знаю как воспроизвести озвученную проблему

**Comment by kartozar** [comment]
воспроизвожу проблему.
адрес скрипта
https://stopad.cgood.ru/script/source?format=routeros&version=v3.0.2@4823b950&redirect_to=127.0.0.1&limit=5000&sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintext&excluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts
потом беру уже сам скрипт, копирую в буфер.
вхожу через веб интерфейс на роутер, и захожу в system script.
добавляю скрипт, вставляю текст.
при нажатии кнопки ок, просто текст скрипта не закрывается.
а вот при нажатии на кнопку run script пишется так:
Couldn’t perform action - script not found (6)

**Comment by tarampampam** [comment]
А если именно шестую строку удалить - то всё работает как надо?

**Comment by kartozar** [comment]
после удаления строки 6 ничего не дает. всёравно говорит ошибка в строке 6.
уже пробовал сам скрипт подставить и думал, что он удачно будет импортировать, но и тут не помогает.
на строку 
:local hostScriptUrl "https://stopad.cgood.ru/script/source?format=routerosversion=v3.0.2@4823b950redirect_to=127.0.0.1limit=5000sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintextexcluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts";

пишет.
expected end of command (line 1 column 7)
видимо что в новой версии или синтаксист поменялся или ещё что не так.

**Comment by tarampampam** [comment]
Могли бы вы показать, скажем - скриншот воспроизводящей проблему? Приведенная вами строка выше не содержит символов `&`, что очень странно

**Comment by kartozar** [comment]
У меня проблемы по зрению. Я полностю не вижу, и использую скринридеры, а потому и не увижу, что на скриншоте. Короче, не смогу я сделать скриншот.

**Comment by sasha2002** [comment]
@tarampampam У него ссылка не правильная, отсюда и ошибки.
@kartozar пробуйте указать :
`:local hostScriptUrl "https://stopad.cgood.ru/script/source?format=routeros&version=v3.0.2@4823b950&redirect_to=127.0.0.1&limit=5000&sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintext&excluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts";`
@kartozar пробуйте что я вам написал.

**Comment by kartozar** [comment]
вот такой скрипт теперь.
:local scriptName "stop_ad.script";
:local backupFileName "before_stopad";
:local logPrefix "[StopAD]";

do {
  /tool fetch check-certificate=no mode=https url=$hostScriptUrl dst-path=("./".$scriptName);
  :delay 3s;
  :if ([:len [/file find name=$scriptName]] > 0) do={
    /system backup save name=$backupFileName;
    :delay 1s;
    :if ([:len [/file find name=($backupFileName.".backup")]] > 0) do={
      /ip dns static remove [/ip dns static find comment=ADBlock];
      /import file-name=$scriptName;
      /file remove $scriptName;
      :log info "$logPrefix AD block script imported, backup file (\"$backupFileName.backup\") created";
    } else={
      :log warning "$logPrefix Backup file not created, importing AD block script stopped";
    }
  } else={
    :log warning "$logPrefix AD block script not downloaded, script stopped";
  }
} on-error={
  :log warning "$logPrefix AD block script download FAILED";
};


и когда его делать
/system script print Clear_Recl  то пишется
expected end of command (line 1 column 7)
тоесть как бы то не было скрипт и в таком варианте не проходит.

**Comment by kartozar** [comment]
`:local hostScriptUrl "https://stopad.cgood.ru/script/source?format=routerosversion=v3.0.2@4823b950redirect_to=127.0.0.1limit=5000sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintextexcluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts";
:local scriptName "stop_ad.script";
:local backupFileName "before_stopad";
:local logPrefix "[StopAD]";

do {
  /tool fetch check-certificate=no mode=https url=$hostScriptUrl dst-path=("./".$scriptName);
  :delay 3s;
  :if ([:len [/file find name=$scriptName]] > 0) do={
    /system backup save name=$backupFileName;
    :delay 1s;
    :if ([:len [/file find name=($backupFileName.".backup")]] > 0) do={
      /ip dns static remove [/ip dns static find comment=ADBlock];
      /import file-name=$scriptName;
      /file remove $scriptName;
      :log info "$logPrefix AD block script imported, backup file (\"$backupFileName.backup\") created";
    } else={
      :log warning "$logPrefix Backup file not created, importing AD block script stopped";
    }
  } else={
    :log warning "$logPrefix AD block script not downloaded, script stopped";
  }
} on-error={
  :log warning "$logPrefix AD block script download FAILED";
};`
даже если делать с консоли /sys script run Clear_Recl
то он не запускается. просто молчит.
в консоли отвечает:
status: failed
тоесть скрипт то уже сохранить можна, но вот он и так не работает.
на /sys script print from=Clear_Recl
говорит примерно так:
Flags: I - invalid 
0 name="Clear_Recl" owner="felcons" policy=ftp,reboot,read,write,policy,test,password,sniff,sensitive 
dont-require-permissions=no last-started=apr/28/2020 17:43:15 run-count=3 
source= 
:local hostScriptUrl "https://stopad.cgood.ru/script/source?format=routerosversion=v3.0.2@4823b950redirect_to=1> 
:local scriptName "stop_ad.script"; 
:local backupFileName "before_stopad"; 
:local logPrefix "[StopAD]"; 

do { 
/tool fetch check-certificate=no mode=https url=$hostScriptUrl dst-path=("./".$scriptName); 
:delay 3s; 
:if ([:len [/file find name=$scriptName]] > 0) do={ 
/system backup save name=$backupFileName; 
:delay 1s; 
:if ([:len [/file find name=($backupFileName.".backup")]] > 0) do={ 
/ip dns static remove [/ip dns static find comment=ADBlock]; 
/import file-name=$scriptName; 
/file remove $scriptName; 
:log info "$logPrefix AD block script imported, backup file (\"$backupFileName.backup\") created"; 
} else={ 
:log warning "$logPrefix Backup file not created, importing AD block script stopped"; 
} 
} else={

**Comment by WhiteO** [comment]
```
## StopAD - Script for blocking advertisements, based on your defined hosts files
## For changing any parameters, please, use this link: https://stopad.cgood.ru/
##
## @github    <https://github.com/tarampampam/mikrotik-hosts-parser>
## @version   v3.0.2@4823b950
##
## Setup this Policy for script: [X] Read [X] Write [X] Policy [X] Test

:local hostScriptUrl "https://stopad.cgood.ru/script/source?format=routeros&version=v3.0.2@4823b950&redirect_to=127.0.0.1&limit=20000&sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintext,https%3A%2F%2Fsomeonewhocares.org%2Fhosts%2Fhosts&excluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts";
:local scriptName "stop_ad.script";
:local backupFileName "before_stopad";
:local logPrefix "[StopAD]";

do {
  /tool fetch check-certificate=no mode=https url=$hostScriptUrl dst-path=("./".$scriptName);
  :delay 3s;
  :if ([:len [/file find name=$scriptName]] > 0) do={
    /system backup save name=$backupFileName;
    :delay 1s;
    :if ([:len [/file find name=($backupFileName.".backup")]] > 0) do={
      /ip dns static remove [/ip dns static find comment=ADBlock];
      /import file-name=$scriptName;
      /file remove $scriptName;
      :log info "$logPrefix AD block script imported, backup file (\"$backupFileName.backup\") created";
    } else={
      :log warning "$logPrefix Backup file not created, importing AD block script stopped";
    }
  } else={
    :log warning "$logPrefix AD block script not downloaded, script stopped";
  }
} on-error={
  :log warning "$logPrefix AD block script download FAILED";
};
```
Скрипт выдает  - AD block script download FAILED
версия 6.46.5, пробовал добавить галочку ftp, результат нет(
Есть предположения что, не так?

**Comment by kartozar** [comment]
переставил скрипт и так тоже не работает.. скрипт выглядит вот так:
:local hostScriptUrl "https://stopad.cgood.ru/script/source?format=routeros&version=v3.0.2@4823b950&redirect_to=127.0.0.1&limit=20000&sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintext,https%3A%2F%2Fsomeonewhocares.org%2Fhosts%2Fhosts&excluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts";
:local scriptName "stop_ad.script";
:local backupFileName "before_stopad";
:local logPrefix "[StopAD]";
do {
  /tool fetch check-certificate=no mode=https url=$hostScriptUrl dst-path=("./".$scriptName);
  :delay 3s;
  :if ([:len [/file find name=$scriptName]] > 0) do={
    /system backup save name=$backupFileName;
    :delay 1s;
    :if ([:len [/file find name=($backupFileName.".backup")]] > 0) do={
      /ip dns static remove [/ip dns static find comment=ADBlock];
      /import file-name=$scriptName;
      /file remove $scriptName;
      :log info "$logPrefix AD block script imported, backup file (\"$backupFileName.backup\") created";
    } else={
      :log warning "$logPrefix Backup file not created, importing AD block script stopped";
    }
  } else={
    :log warning "$logPrefix AD block script not downloaded, script stopped";
  }
} on-error={
  :log warning "$logPrefix AD block script download FAILED";
Ошибку выдает в строке 24.
пишет error line 24 collum 60.

**Comment by tarampampam** [comment]
На площадке `cgood.ru` наблюдаются проблемы с производительностью (ребята пустили к ним на сервер бесплатно, поэтому и требовать что-либо сложно). Сейчас перезапустил демона - заработал. Если что - есть альтернатива в виде `stopad.hook.sh`
