### ISSUE TITLE
The script is great but can we change it in the way so this return a list of IP's which to be filtered in RAW?

### ISSUE THREAD

**Issue by NAS-warrior** [tarampampam/mikrotik-hosts-parser#42]
### Is your feature request related to a problem?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like

> A clear and concise description of what you want to happen.

## Additional context

> Add any other context about the feature request here.

**Comment by tarampampam** [comment]
@NAS-warrior Please, fill up issue template with more detailed example
