### ISSUE TITLE
источник hpHosts  не качается

### ISSUE THREAD

**Issue by popowsergei** [tarampampam/mikrotik-hosts-parser#45]
hpHosts 
 https://hosts-file.net/ad_servers.txt 

перестал скачивается

**Comment by GAmblerDice** [comment]
Судя по этой теме давненько уже
https://www.reddit.com/r/pihole/comments/fsygwy/hostsfilenet_down/
можно попробывать заменить на 
https://raw.githubusercontent.com/evankrob/hosts-filenetrehost/master/ad_servers.txt
но не уверен будет ли он маинтейниться.

Подозреваю, что можно убрать из дефолтного сорс листа для парсера

**Comment by popowsergei** [comment]
>но не уверен будет ли он маинтейниться.
работает, думаю можно и заменить на него пока

**Comment by tarampampam** [comment]
Thx for your report!
