### ISSUE TITLE
После отработки скрипта на телевизоре Самсунг перестала работать история поиска и поисковые предложения

### ISSUE THREAD

**Issue by Stepperer** [tarampampam/mikrotik-hosts-parser#50]
То есть скрипт-то сам отработал. И режет всякую фигню как надо. Но на ящике история поиска всегда пустая, предложения по мере набора больше не возникают, для проведения поиска надо набрать фразу полностью (на этом клятом пульте-обрубке-то =\) и нажать "искать" - и вот только тогда оно снесется. И то не сразу

Может что-то надо из блокировки прост убрать? Какой именно домен Ютуб на телеках для истории поиска использует?

**Comment by TerAnYu** [comment]
Видимо только через WireShark проследить куда он обращается.
https://wiki.merionet.ru/seti/6/perexvat-paketov-na-mikrotik/

**Comment by Stepperer** [comment]
Спасибо, вайршарк решает )

Виновник торжества - clients1.google.com

Если его разрешить - начинает работать предложка и история поиска.

Вопрос. Черт с ним пусть следит и пишет. Если я оставлю его включенным, рекламу на Ютубе он мне не запустит обратно?

**Comment by Stepperer** [comment]
Отвечая на свой же ответ - запустит =\

**Comment by GAmblerDice** [comment]
Тут наверно выход, только если проксировать с микрота это куда-нить, пропуская clients1.google.com/search , а остальное оставлять на 127.0.0.1, и наверно это возможно сделать на микротовском l7 firewal'е но надо у гуру спрашивать, как сделать это верно.
И мой вариант скорее всего будет сложно поддерживать, потому что нет гарантии что гугл не сменит урл для саджеста
