### ISSUE TITLE
Import Pi-Hole lists

### ISSUE THREAD

**Issue by iG8R** [tarampampam/mikrotik-hosts-parser#54]
Hi.
Could it be possible to implement importing functionality of Pi-Hole lists?
E.g. https://www.sunshine.it/blacklist.txt from https://www.sunshine.it/disable-youtube-video-advertising-with-pi-hole-finally-video-2/
Best regards,
Igor.

**Comment by tarampampam** [comment]
Only "hosts" file is supported (de-facto standard). But we are open for your PR!
