### ISSUE TITLE
Не работает скрипт на Mikrotik RBD52G-5HacD2HnD  FW: 6.47.4

### ISSUE THREAD

**Issue by gri8341** [tarampampam/mikrotik-hosts-parser#56]
При попытке использовать скрипт с страницы: https://stopad.hook.sh/
на: Mikrotik RBD52G-5HacD2HnD fw: 6.47.4  - в логах появляется ошибка: [StopAD] AD block script download FAILED

![image](https://user-images.githubusercontent.com/73105340/96426074-6d21cc00-1205-11eb-862d-5aef6a8cdcd2.png)

**Comment by GAmblerDice** [comment]
А можно посмотреть сам скрипт, версия микрота у меня таже, вроде все работет как должно, курлом подергал с дефолтным урлом, вроде тоже все вернулось.

**Comment by referi** [comment]
в логах появляется ошибка: [StopAD] AD block script download FAILED
у меня такое было пару раз, когда игрался со списками, но в целом загружает и применяет список корректно. Только рекламу совсем не блокирует на ютубе и на некоторых сайтах тоже.

**Comment by deGoyan** [comment]
Та же проблема. При этом, если вручную попытаться скачать файл 
`/tool fetch check-certificate=no mode=https url="https://stopad.hook.sh/script/source?format=routeros&version=v3.0.2@4823b950&redirect_to=127.0.0.1&limit=100000&sources_urls=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Ftarampampam%2Fmikrotik-hosts-parser%40master%2F.hosts%2Fbasic.txt,https%3A%2F%2Fraw.githubusercontent.com%2Fcrazy-max%2FWindowsSpyBlocker%2Fmaster%2Fdata%2Fhosts%2Fspy.txt,https%3A%2F%2Fadaway.org%2Fhosts.txt,https%3A%2F%2Fwww.malwaredomainlist.com%2Fhostslist%2Fhosts.txt,https%3A%2F%2Fpgl.yoyo.org%2Fadservers%2Fserverlist.php%3Fhostformat%3Dhosts%26showintro%3D0%26mimetype%3Dplaintext,https%3A%2F%2Fsomeonewhocares.org%2Fhosts%2Fhosts,http%3A%2F%2Fwinhelp2002.mvps.org%2Fhosts.txt&excluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allrouters,ip6-allhosts" dst-path=("./".$scriptName)`
то выдает ошибку
`failure: closing connection: <301 Moved Permanently "/script/sourceformat=routeros&version=v3.0.2@4823b950&redirect_to=127.0.0.1&limit=100000&sources_urls=https:/cdn.jsdelivr.net/gh/tarampampam/mikrotik-hosts-parser@master/.hosts/b
aw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt,https:/adaway.org/hosts.txt,https:/www.malwaredomainlist.com/hostslist/hosts.txt,https:/pgl.yoyo.org/adservers/serverlist.php%3Fhostformat=hosts&showint
intext,https:/someonewhocares.org/hosts/hosts,http:/winhelp2002.mvps.org/hosts.txt&excluded_hosts=localhost,localhost.localdomain,broadcasthost,local,ip6-localhost,ip6-loopback,ip6-localnet,ip6-mcastprefix,ip6-allnodes,ip6-allroute`

**Comment by GAmblerDice** [comment]
301 редирект, курлом почему то не воспроизводиться, но так же я вижу что вручную ты подкидываешь переменную о которой он знать не может, ибо вне скрипта не объявлена она. Попробуй dst-path=("./".stop_ad.script)

**Comment by deGoyan** [comment]
> Попробуй dst-path=("./".stop_ad.script)

Переменную я задавал в терминале. Если задать явно, ничего не меняется. RoS 6.47.7

**Comment by GAmblerDice** [comment]
Хм забавная история, копирую урл в консоль микротика и у меня съедается при пасте знак ?, и я его даже вручную поставить не могу) И причем выше предложеная отбивка говорит что у вас такое же поведение.
