### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by TheTitanrain** [tarampampam/mikrotik-hosts-parser#57]
## Describe the bug

Ошибка `Source <https://someonewhocares.org/hosts/hosts> error: Get https://someonewhocares.org/hosts/hosts: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`.
Хотя переходишь по url в браузере и всё открывается.
Пробую на stopad.cgood.ru.

### Expected behaviour

Вернулся скрипт

### Actual behaviour

Ошибка.

### Steps to reproduce the behavior:

Отметить на сайте stopad.cgood.ru пункт omeonewhocares.org

**Comment by tarampampam** [comment]
Проблема с маршрутами на хосте или провайдера услуг. Поправить в данный момент невозможно
