### ISSUE TITLE
Можно ли сконвертировать подписки https://adblockplus.org/ru/subscriptions для Mikrotik?

### ISSUE THREAD

**Issue by sarkan20** [tarampampam/mikrotik-hosts-parser#59]
### Is your feature request related to a problem?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like

> A clear and concise description of what you want to happen.

## Additional context

> Add any other context about the feature request here.

**Comment by tarampampam** [comment]
Написав отдельный конвертер или если вы реализуете этот функционал самостоятельно, предложив изменения в виде PR в данный репозиторий. В обозримой перспективе делать это своими силами не планировал.
