### ISSUE TITLE
Cервисы телеметрии от MS  

### ISSUE THREAD

**Issue by popowsergei** [tarampampam/mikrotik-hosts-parser#8]
ссылка на Cервисы телеметрии от MS   сдохла

**Comment by popowsergei** [comment]
можно поменять на https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/win7/spy.txt

**Comment by popowsergei** [comment]
вот актуальные
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/extra.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/update.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win81/extra.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win81/spy.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win81/update.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win7/extra.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win7/spy.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win7/update.txt

**Comment by tarampampam** [comment]
Решение: #10
