### ISSUE TITLE
Ошибка при работе скрипта

### ISSUE THREAD

**Issue by Eurgen** [tarampampam/mikrotik-hosts-parser#9]
Добрый день!
Скрипт перестал обрабатывать листы, падет в ошибку. Есть возможность поправить?
примеры листов:
https://cdn.raletag.gq/rueasyhosts.txt
https://cdn.raletag.gq/yoyohosts.txt
https://cdn.raletag.gq/malwaredomainlisthosts.txt

## Error :: https://cdn.raletag.gq/rueasyhosts.txt :: cURL error 28: Operation timed out after 10000 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by tarampampam** [comment]
`https://stopad.cgood.ru/script/source?format=routeros&version=2.0.2&sources_urls=https%3A%2F%2Fcdn.raletag.gq%2Frueasyhosts.txt,https%3A%2F%2Fcdn.raletag.gq%2Fyoyohosts.txt,https%3A%2F%2Fcdn.raletag.gq%2Fmalwaredomainlisthosts.txt&excluded_hosts=localhost` - работает

`https://stopad.cgood.ru/script/source?format=routeros&version=2.0.2&sources_urls=https%3A%2F%2Fcdn.raletag.gq%2Frueasyhosts.txt,https%3A%2F%2Fcdn.raletag.gq%2Fyoyohosts.txt,https%3A%2F%2Fcdn.raletag.gq%2Fmalwaredomainlisthosts.txt&excluded_hosts=localhost` - работает

Проблема не воспроизводится.

Пожалуйста, дополните более полной информацией, и создайте новый issue.
